root: true
env:
  es2021: true
  node: true
  browser: true
  jest: true
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
