version: '3.8'

services:
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db
  blog-backend:
    image: blog-backend
    build: ./backend/
    ports:
      - 3001:3000
    volumes:
      - ./backend/:/usr/src/app
    environment:
      - PORT=3001
      - NODE_ENV=production
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - SECRET=k12345
    container_name: blog-backend
  blog-frontend:
    image: blog-frontend
    build: ./frontend/
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    container_name: blog-frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: blog-reverse-proxy-full
